# ---
# Keycloak Playground
# ===
# En este archivo se detalla la arquitectura del proyecto.
# Esta conformado por dos servicios:
#   1. `Keycloak`: El servicio de `keycloak` funcionando sobre `jboss`.
#   2. `Postgres`: La base de datos donde se guarda la información de `Postgres`.
# ---
version: '3.7'
# --- SERVICES --- #
services:
  # --- NGINX
  nginx:
    image: nginx:1.15.1
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificates/keycloak.demo.conatest.click.fullchain.crt:/etc/nginx/keycloak.demo.conatest.click.crt
      - ./certificates/keycloak.demo.conatest.click.key:/etc/nginx/keycloak.demo.conatest.click.key
    ports:
      - '80:80'
      - '443:443'
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - keycloak
    networks:
      - backend
  # --- Keycloak
  keycloak:
    image: jboss/keycloak:6.0.1
    restart: always
    container_name: keycloak
    volumes:
      - ./keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_SCHEMA=public
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_VENDOR=postgres
      - PROXY_ADDRESS_FORWARDING=true
      - JBOSS_HOME=/opt/jboss/keycloak
    depends_on:
      - postgres
    ports:
      - '8080:8080'
      - '8443:8443'
    networks:
      - backend
  # --- Database
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=keycloak 
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - backend
  # --- Adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - backend
# --- VOLUMES --- #
volumes:
  postgres_volume:
# --- NETWORKS --- #
networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: 172.18.254.0/24
