# ---
# Keycloak Playground
# ===
# En este archivo se detalla la arquitectura del proyecto.
# Esta conformado por dos servicios:
#   1. `Keycloak`: El servicio de `keycloak` funcionando sobre `jboss`.
#   2. `Postgres`: La base de datos donde se guarda la información de `Postgres`.
# ---
version: '3.7'
# --- SERVICES --- #
services:
  # --- NGINX
  nginx:
    image: nginx:1.15.1
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
  # --- Keycloak
  keycloak:
    build: .
    restart: always
    container_name: keycloak
    environment:
      - KEYCLOAK_USER={{keycloak_username}}
      - KEYCLOAK_PASSWORD={{keycloak_password}}
      - DB_ADDR={{db_addr}}
      - DB_PORT={{db_port}}
      - DB_DATABASE={{keycloak_db_name}}
      - DB_SCHEMA={{keycloak_db_schema}}
      - DB_USER={{db_user}}
      - DB_PASSWORD={{db_password}}
      - DB_VENDOR=postgres
    depends_on:
      - postgres
    ports:
      - '8080:8080'
      - '8443:8443'
    networks:
      - backend
  # --- Database
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD={{db_password}}
      - POSTGRES_USER={{db_user}}
      - POSTGRES_DB={{keycloak_db_name}} 
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - backend
  # --- Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - backend
# --- VOLUMES --- #
volumes:
  postgres_volume:
# --- NETWORKS --- #
networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: 172.18.254.0/24
