all:
  children:
    local:
      hosts:
        127.0.0.1:
  vars:
    # Database vars
    db_addr: postgres
    db_port: 5432
    db_user: '{{ user }}'
    db_password: '{{ password }}'
    # Keycloak vars
    keycloak_username: '{{ user }}'
    keycloak_password: '{{ password }}'
    keycloak_db_name: keycloak
    keycloak_db_schema: public
    # Docker compose vars
    docker_compose_build: no
    docker_compose_project_src: '.'
    docker_compose_state: present
    docker_compose_remove_volumes: yes
    # OpenSSL pirvate key vars
    openssl_privatekey_path: ../certificates/letsencrypt.key
    openssl_csr_privatekey_path: '../certificates/{{ domain }}.key'
    # OpenSSL CSR vars
    openssl_csr_path: '../certificates/{{ domain }}.csr'
    openssl_csr_country_name: '{{ country_name }}'
    openssl_csr_organization_name: '{{ organization_name }}'
    openssl_csr_email_address: '{{ email }}'
    openssl_csr_common_name: '{{ domain }}'
    # Acme certificate vars
    acme_certificate_account_key_src: '{{ openssl_privatekey_path }}'
    acme_certificate_account_email: '{{ email }}'
    acme_certificate_csr: '{{ openssl_csr_path }}'
    acme_certificate_dest: '../certificates/{{ domain }}.crt'
    acme_certificate_chain_dest: '../certificates/{{ domain }}.chain.crt'
    acme_certificate_fullchain_dest: '../certificates/{{ domain }}.fullchain.crt'
    acme_certificate_directory: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    acme_certificate_remaining_days: 30 
    # AWS Route53 vars
    route53_zone: '{{ zone }}'
    # Ansible vars
    ansible_python_interpreter: '{{ python_interpreter | default("/usr/bin/python") }}'


